detect:
  # 徘徊检测控制参数, 置信度阈值(conf_thres)和交并比阈值(iou_thres), 最终在utils.commons.ImageHandler.process_output使用
  # 徘徊检测过滤参数, 目标过滤阈值(filter_size), 在self.filter_by_size使用
  conf_thres: 0.5
  iou_thres: 0.5
  filter_size: 48

areas:
  # 徘徊控制区域, 最终在utils.commons.ImageHandler.is_in_poly中使用
  # 可设置多个区，API调用中指定区域会覆盖此处设置的缺省参数
  # 区域定义方式:
  #    - 单点：控制区域为一点
  #    - 两点：以两点为对角线的矩形区域
  #    - 三点及以上：顺时针多边形顶点
  # 侵入算法中，若未定义控制区域，则自动设置全图均为控制区域
  '0': [[100,150],[800,1200]]
  #'1': [[960,960]]
  '2': [[196, 139], [447, 79], [1155, 550], [764, 650]]
  #'3': [[0,0],[100,50],[200,150],[300,350], [400,750], [500, 1550], [600,1200], [700, 0]]
