detect:
  # 目标检测控制参数, 置信度阈值(conf_thres)和交并比阈值(iou_thres), 最终在self.process_output使用
  # 目标检测过滤参数, 目标过滤阈值(filter_size), 在self.filter_by_size使用
  conf_thres: 0.5
  iou_thres: 0.5
  filter_size: 1

digit:
  # 雷击计数器控制参数, 置信度阈值(conf_thres)和交并比阈值(iou_thres), 最终在self.process_output使用
  conf_thres: 0.2
  iou_thres: 0.5

pose2:
  # 避雷针表记2, 置信度阈值(conf_thres)和交并比阈值(iou_thres), 最终在self.process_box_output使用
  conf_thres: 0.5
  iou_thres: 0.5